apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-broker
data:
  hmq.config: |
    {
      "workerNum": 4096,
      "port": "1883",
      "host": "0.0.0.0",
      "plugins": ["authhttp","kafka"]
    }

